### ISSUE TITLE
injex.js closes when opened with cmd

### ISSUE THREAD

**Issue by fwegewgegergre** [YourPalNicky/DungeonBot#1]

**Comment by YourPalNicky** [comment]
Please reply with any errors you may be getting. Please make sure that you have node.js installed and the discord.js and Systeminformation repositories installed inside of the bot folder as listed in the installation instructions. I will check if i get the same error by testing later today.

**Comment by YourPalNicky** [comment]
Please reply with any errors you may be getting. Please make sure that you have node.js installed and the discord.js and Systeminformation repositories installed inside of the bot folder as listed in the installation instructions. I will check if i get the same error by testing later today.
